#pragma once

enum GUI_IDs
{


	GUI_ID_MAINMENU_SINGLE_BUTTON = 101,
	GUI_ID_MAINMENU_LAN_BUTTON = 102,
	GUI_ID_MAINMENU_OPTIONS_BUTTON = 103,
	GUI_ID_MAINMENU_EXIT_BUTTON = 104,

	GUI_ID_SINGLEMENU_PREVIOUS_BUTTON = 201, 
	GUI_ID_SINGLEMENU_NEXT_BUTTON = 202, 
	GUI_ID_SINGLEMENU_PLAY_BUTTON = 203, 


	GUI_ID_OPTIONSMENU_VIDEODRIVER_TAB = 301,
	GUI_ID_OPTIONSMENU_VIDEODRIVER_COMBO,
	GUI_ID_OPTIONSMENU_VIDEOMODE_COMBO,
	GUI_ID_OPTIONSMENU_FULLSCREEN_CHECKBOX,
	GUI_ID_OPTIONSMENU_32BITS_CHECKBOX,
	GUI_ID_OPTIONSMENU_VSYNC_CHECKBOX,
	GUI_ID_OPTIONSMENU_MULTISAMPLE_BAR,
	GUI_ID_OPTIONSMENU_GAMMA_BAR,
	GUI_ID_OPTIONSMENU_APPLY_BUTTON,

	GUI_ID_OPTIONSMENU_KEYBINDINGS_TABLE = 401,

	GUI_ID_LANMENU_TABLE = 501,
	GUI_ID_LANMENU_JOIN_BUTTON,
	GUI_ID_LANMENU_CREATE_BUTTON,
	GUI_ID_LANMENU_CREATENEWGAME_MESSAGEBOX,
	GUI_ID_LAN_CREATENEWGAME_GAMENAME_EDITBOX,
	GUI_ID_LAN_CREATENEWGAME_HOSTNAME_EDITBOX,

	GUI_ID_LAN_TEST_BUTTON,

	GUI_ID_LANMENU_JOINGAME_MESSAGEBOX,
	GUI_ID_LAN_JOINGAME_NICKNAME_EDITBOX,

	GUI_ID_LAN_JOINIP_BUTTON,
	GUI_ID_LAN_JOINIP_MESSAGEBOX,
	GUI_ID_LAN_JOINIP_IP_EDITBOX,
	GUI_ID_LAN_JOINIP_NICKNAME_EDITBOX,

	GUI_ID_LANFINAL_CHAT_EDITBOX,
	GUI_ID_LANFINAL_INPUTCHAT_EDITBOX,
	GUI_ID_LANFINAL_STARTGAME_BUTTON,
	GUI_ID_LANFINAL_READY_BUTTON,
	GUI_ID_LANFINAL_ADDBOT_BUTTON,
	GUI_ID_LANFINAL_REMOVEBOT_BUTTON,

	GUI_ID_GAMEMENU_CONTAINER = 601,
	GUI_ID_GAMEMENU_CONTINUE_BUTTON,
	GUI_ID_GAMEMENU_EXIT_BUTTON,

	GUI_ID_SCOREBOARD_CONTAINER = 701,
};


